var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[b]=a.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var b=0;return $jscomp.iteratorPrototype(function(){return b<c.length?{done:!1,value:c[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var b=c[Symbol.iterator];return b?b.call(c):$jscomp.arrayIterator(c)};
$jscomp.polyfill=function(c,b,a,e){if(b){a=$jscomp.global;c=c.split(".");for(e=0;e<c.length-1;e++){var f=c[e];f in a||(a[f]={});a=a[f]}c=c[c.length-1];e=a[c];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(a,c,{configurable:!0,writable:!0,value:b})}};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function b(){this.batch_=null}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;b.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};b.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var a=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){a(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=
this.batch_;this.batch_=[];for(var a=0;a<d.length;++a){var e=d[a];delete d[a];try{e()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var e=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{d(a.resolve,a.reject)}catch(h){a.reject(h)}};e.prototype.createResolveAndReject_=function(){function d(d){return function(b){e||(e=!0,d.call(a,b))}}var a=this,e=
!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};e.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.settleSameAsPromise_(d);else{var a;a:switch(typeof d){case "object":a=null!=d;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};e.prototype.resolveToNonPromiseObj_=function(d){var a=void 0;try{a=d.then}catch(h){this.reject_(h);return}"function"==
typeof a?this.settleSameAsThenable_(a,d):this.fulfill_(d)};e.prototype.reject_=function(d){this.settle_(2,d)};e.prototype.fulfill_=function(d){this.settle_(1,d)};e.prototype.settle_=function(d,a){if(0!=this.state_)throw Error("Cannot settle("+d+", "+a|"): Promise already settled in state"+this.state_);this.state_=d;this.result_=a;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=this.onSettledCallbacks_,a=0;a<d.length;++a)d[a].call(),
d[a]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(d){var a=this.createResolveAndReject_();d.callWhenSettled_(a.resolve,a.reject)};e.prototype.settleSameAsThenable_=function(d,a){var e=this.createResolveAndReject_();try{d.call(a,e.resolve,e.reject)}catch(k){e.reject(k)}};e.prototype.then=function(d,a){function b(a,d){return"function"==typeof a?function(d){try{c(a(d))}catch(q){f(q)}}:d}var c,f,g=new e(function(d,a){c=d;f=a});this.callWhenSettled_(b(d,c),
b(a,f));return g};e.prototype["catch"]=function(d){return this.then(void 0,d)};e.prototype.callWhenSettled_=function(d,a){function e(){switch(b.state_){case 1:d(b.result_);break;case 2:a(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?f.asyncExecute(e):this.onSettledCallbacks_.push(function(){f.asyncExecute(e)})};e.resolve=function(a){return a instanceof e?a:new e(function(d,e){d(a)})};e.reject=function(a){return new e(function(d,e){e(a)})};
e.race=function(a){return new e(function(d,b){for(var c=$jscomp.makeIterator(a),f=c.next();!f.done;f=c.next())e.resolve(f.value).callWhenSettled_(d,b)})};e.all=function(a){var d=$jscomp.makeIterator(a),b=d.next();return b.done?e.resolve([]):new e(function(a,c){function f(d){return function(b){g[d]=b;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,e.resolve(b.value).callWhenSettled_(f(g.length-1),c),b=d.next();while(!b.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(e.$jscomp$new$AsyncExecutor=function(){return new b});
return e},"es6-impl","es3");var TesouroGraficosModule;(function(c){c.AboutController=function(b){this.$scope=b}})(TesouroGraficosModule||(TesouroGraficosModule={}));var TypeIndice;(function(c){c[c.Selic=100]="Selic"})(TypeIndice||(TypeIndice={}));
(function(c){c.FormatConfig=function(b){b.formatDate=function(a){return a?moment(a).format("DD/MM/YYYY"):""};b.parseDate=function(a){if(null==a||0==a.length)return null;a=moment(a,"DD/MM/YYYY",!0);return a.isValid()?a.toDate():new Date(NaN)}}})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(a,b){var e=this;this.$scope=a;this.$routeParams=b;this.vm=new c.ChartViewModel;this.titlePage="Gr\u00e1fico de pre\u00e7os e taxas dos t\u00edtulos vencidos do Tesouro Direto";this.chartHandler=new c.ChartHandler("chart-container","Gr\u00e1fico dos T\u00edtulos Vencidos do Tesouro Direto");var d=this.$routeParams.Bond,g=this.$routeParams.Date,h=this.$routeParams.Cupom;this.vm.LoadData().then(function(){var b=e.vm.BondList.filter(function(a){return a.Vencido}).sort(function(a,
d){return a.Name<d.Name?-1:1});e.vm.BondList=b;e.chartHandler.SetBondList(e.vm.BondList);e.chartHandler.SetIndiceList(e.vm.IndicesList);e.chartHandler.Init();var c=e.chartHandler.GetBondByNameMaturityDate("prefixado",new Date("2010-01-01"),!1);if(void 0!=d&&void 0!=g){var b=!1,f=null,m=moment(g,"DDMMYYYY");null!=h&&"cupom-de-juros"===h.toLowerCase()&&(b=!0);null==m||isNaN(m.valueOf())||(f=e.chartHandler.GetBondByNameMaturityDate(d,m.toDate(),b));null!=f&&(c=f);c.IsTaxVisible=c.IsTaxAvaregeVisible=
c.IsPriceVisible=c.IsPriceAvaregeVisible=!0;e.chartHandler.LoadBond(c).then(function(){e.setStatus(c)})}else c.IsTaxVisible=c.IsTaxAvaregeVisible=c.IsPriceVisible=c.IsPriceAvaregeVisible=!0,e.chartHandler.LoadBond(c);a.$apply()});$("#boxes-chart").hide()};b.prototype.OpenChart=function(a){var e=this.chartHandler.GetActivedBonds();a=this.chartHandler.GetBondById(a);3<=e.length&&!a.IsSelected()||(a.IsTaxVisible=a.IsTaxAvaregeVisible=a.IsPriceVisible=a.IsPriceAvaregeVisible=!a.IsSelected(),1<=e.length&&
(this.vm.CompareMaturityBond=!1,this.vm.DateBuy=null),this.chartHandler.LoadBond(a))};b.prototype.setStatus=function(a){a=0<this.vm.SelectedBondNames().length?this.vm.SelectedBondNames()+" -":"";document.title=a+" "+this.titlePage};b.prototype.OpenIndice=function(a,e){this.chartHandler.LoadIndice(TypeIndice.Selic,e)};b.prototype.UpdateDateBuy=function(){this.chartHandler.SetLinearPrice(this.vm.DateBuy,this.vm.CompareMaturityBond)};b.prototype.CompareWithMaturityBond=function(){var a=this;this.chartHandler.SetLinearPrice(this.vm.DateBuy,
this.vm.CompareMaturityBond).then(function(e){debugger;a.vm.DateBuy=a.vm.MinDate=e.StartDate})};c.ChartTitulosVencidoController=b})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(){this.MinDate=new Date(2016,1,1);this.MaxDate=new Date;this.HistoricalData=this.CompareMaturityBond=!1};b.prototype.CanShowComparation=function(){return this.BondList?1==this.BondList.filter(function(a){return"prefixado"==a.Bond&&a.IsSelected()&&!a.Cupom}).length:!1};b.prototype.SelectedBondNames=function(){return this.BondList?this.BondList.filter(function(a){return a.IsSelected()}).map(function(a){return a.ShortName}).join(" - "):""};b.prototype.OnlyWeekDays=function(a){a=
a.getDay();return 0!==a&&6!==a};b.prototype.LoadData=function(){var a=this;return new Promise(function(e){$.getJSON(c.DataServiceHelper.GetBondsList(),function(e){a.BondList=e.map(function(a){var d=new c.Bond;d.Id=a.Id;d.Bond=a.Bond;d.MaturityDate=moment(a.MaturityDate).toDate();d.Cupom=a.Cupom;d.File=a.File;d.Name=a.Name;d.ShortName=a.ShortName;d.IsPriceVisible=a.IsPriceVisible;d.IsPriceAvaregeVisible=a.IsPriceAvaregeVisible;d.IsTaxVisible=a.IsTaxVisible;d.IsTaxAvaregeVisible=a.IsTaxAvaregeVisible;
d.Vencido=a.Vencido;d.StarDate=moment(a.StartDate).toDate();return d})}).then(function(){return $.getJSON(c.DataServiceHelper.GetIndices(),function(b){a.IndicesList=b.map(function(a){var d=new c.Indice;d.Type=a.Type;d.IsSelected=a.IsSelected;d.File=a.File;d.Name=a.Name;d.DisplayName=a.DisplayName;return d});e()})})})};c.ChartViewModel=b})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){c.RouteConfig=function(b){b.caseInsensitiveMatch=!0;b.when("/home",{templateUrl:"Pages/Chart.html",controller:"ChartController",controllerAs:"chartCtr"}).when("/titulo/:Bond/:Date",{templateUrl:"Pages/Chart.html",controller:"ChartController",controllerAs:"chartCtr"}).when("/titulo/:Bond/:Date/:Cupom",{templateUrl:"Pages/Chart.html",controller:"ChartController",controllerAs:"chartCtr"}).when("/titulo/vencido",{templateUrl:"Pages/Chart.html",controller:"ChartTitulosVencidoController",controllerAs:"chartCtr"}).when("/titulo/vencido/:Bond/:Date",
{templateUrl:"Pages/Chart.html",controller:"ChartTitulosVencidoController",controllerAs:"chartCtr"}).when("/titulo/vencido/:Bond/:Date/:Cupom",{templateUrl:"Pages/Chart.html",controller:"ChartTitulosVencidoController",controllerAs:"chartCtr"}).when("/sobre",{templateUrl:"Pages/about.html",controller:"AboutController"}).when("/contato",{templateUrl:"Pages/contact.html",controller:"ContactController"}).when("/indice/:Indice",{templateUrl:"Pages/Indice.html",controller:"IndiceController",controllerAs:"IndiceCtr"}).otherwise({redirectTo:"/home"})};
c.ThemeConfig=function(b){b.definePalette("customAccent",{50:"#072d26",100:"#0a4438",200:"#0d5a4a",300:"#10705d",400:"#14866f",500:"#179d82",600:"#1dc9a6",700:"#21dfb8",800:"#37e2bf",900:"#4ee5c7",A100:"#1dc9a6",A200:"#1AB394",A400:"#179d82",A700:"#64e8ce"});b.theme("default").primaryPalette("blue-grey").accentPalette("customAccent")}})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(a,e){var b=this;this.$scope=a;this.$routeParams=e;this.vm=new c.IndiceViewModel;this.vm.Title="Hist\u00f3rico Taxa Juros Selic";this.vm.SubTitle="Dados Di\u00e1rios desde 01/07/1996";this.vm.Text="A taxa SELIC (Sistema Especial de Liquida\u00e7\u00e3o e de Cust\u00f3dia) \u00e9 um \u00edndice pelo qual as taxas de juros cobradas pelos bancos no Brasil se balizam. A taxa \u00e9 uma ferramenta de pol\u00edtica monet\u00e1ria utilizada pelo Banco Central do Brasil para atingir a meta das taxas de juros estabelecida pelo Comit\u00ea de Pol\u00edtica Monet\u00e1ria (Copom).";
this.chartHandler=new c.ChartHandler("indice-container","Hist\u00f3rico Taxa Selic - Desde 1996");void 0!=this.$routeParams.Indice&&this.LoadData().then(function(d){b.CreatSerie(d);a.$apply()})};b.prototype.CreatSerie=function(a){this.chartHandler.AddSerie({id:"selicFull",name:"Taxa Selic",type:"spline",data:a,yAxis:0,tooltip:{valueSuffix:" %",shared:!1}});this.chartHandler.DisableAxi("axyPrice")};b.prototype.LoadData=function(){return new Promise(function(a){var b,f=(new Date).yyyymmdd()+"|selicFull";
(f=sessionStorage.getItem(f))?(b=JSON.parse(f),a(b)):$.getJSON(c.DataServiceHelper.GetSelicFull(),function(d){b=d.map(function(a){return[a.Date,a.Value]});a(b)})})};c.IndiceController=b})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(){};b.TesouroGragicosApp=angular.module("TesouroGragicosApp",["ngMaterial","ngMessages","ngRoute"]);c.ChartAngularModule=b;var a=function(a,b){var d=this;this.$scope=a;this.$routeParams=b;this.vm=new c.ChartViewModel;this.titlePage="Gr\u00e1fico de pre\u00e7os e taxas dos t\u00edtulos do Tesouro Direto";this.chartHandler=new c.ChartHandler("chart-container","Gr\u00e1fico dos T\u00edtulos do Tesouro Direto");var e=this.$routeParams.Bond,f=this.$routeParams.Date,k=this.$routeParams.Cupom;
this.vm.LoadData().then(function(){var b=d.vm.BondList.filter(function(a){return!a.Vencido}).sort(function(a,d){return a.Name<d.Name?-1:1});d.vm.BondList=b;d.chartHandler.SetBondList(d.vm.BondList);d.chartHandler.SetIndiceList(d.vm.IndicesList);d.chartHandler.Init();var c=d.chartHandler.GetBondByNameMaturityDate("prefixado",new Date("2023-01-01"),!1);if(void 0!=e&&void 0!=f){var b=!1,h=null,g=moment(f,"DDMMYYYY");null!=k&&"cupom-de-juros"===k.toLowerCase()&&(b=!0);null==g||isNaN(g.valueOf())||(h=
d.chartHandler.GetBondByNameMaturityDate(e,g.toDate(),b));null!=h&&(c=h);c.IsTaxVisible=c.IsTaxAvaregeVisible=c.IsPriceVisible=c.IsPriceAvaregeVisible=!0;d.chartHandler.LoadBond(c).then(function(){d.setStatus(c)})}else c.IsTaxVisible=c.IsTaxAvaregeVisible=c.IsPriceVisible=c.IsPriceAvaregeVisible=!0,d.chartHandler.LoadBond(c);a.$apply()});a.$on("$viewContentLoaded",function(){$(".md-datepicker-input").mask("00/00/0000")})};a.prototype.OpenChart=function(a){var b=this.chartHandler.GetActivedBonds();
a=this.chartHandler.GetBondById(a);3<=b.length&&!a.IsSelected()||(a.IsTaxVisible=a.IsTaxAvaregeVisible=a.IsPriceVisible=a.IsPriceAvaregeVisible=!a.IsSelected(),1<=b.length&&(this.vm.CompareMaturityBond=!1,this.vm.DateBuy=null),this.chartHandler.LoadBond(a))};a.prototype.setStatus=function(a){a=0<this.vm.SelectedBondNames().length?this.vm.SelectedBondNames()+" -":"";document.title=a+" "+this.titlePage};a.prototype.OpenIndice=function(a,b){this.chartHandler.LoadIndice(TypeIndice.Selic,b)};a.prototype.UpdateDateBuy=
function(){this.chartHandler.SetLinearPrice(this.vm.DateBuy,this.vm.CompareMaturityBond)};a.prototype.CompareWithMaturityBond=function(){var a=this;this.chartHandler.SetLinearPrice(this.vm.DateBuy,this.vm.CompareMaturityBond).then(function(b){debugger;a.vm.DateBuy=a.vm.MinDate=b.StartDate})};c.ChartController=a;b.TesouroGragicosApp.controller("ChartController",["$scope","$routeParams",a]);b.TesouroGragicosApp.controller("AboutController",["$scope",c.AboutController]);b.TesouroGragicosApp.controller("ContactController",
["$scope",c.ContactController]);b.TesouroGragicosApp.controller("IndiceController",["$scope","$routeParams",c.IndiceController]);b.TesouroGragicosApp.controller("ChartTitulosVencidoController",["$scope","$routeParams",c.ChartTitulosVencidoController]);b.TesouroGragicosApp.config(["$routeProvider",c.RouteConfig]);b.TesouroGragicosApp.config(["$mdDateLocaleProvider",c.FormatConfig]);b.TesouroGragicosApp.config(["$mdThemingProvider",c.ThemeConfig])})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(a,b){var c=this;this.titulo=b;this.createChart=function(a){var d={chart:{zoomType:"x",renderTo:""},title:{text:c.titulo},rangeSelector:{selected:4,buttons:[{type:"month",count:1,text:"1 m\u00eas"},{type:"month",count:3,text:"3 meses"},{type:"month",count:6,text:"6 meses"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1 ano"},{type:"all",text:"tudo"}],buttonTheme:{width:60}},xAxis:{type:"datetime",dateTimeLabelFormats:{day:"%d.%m.%y",week:"%d.%m.%y",month:"%d.%m.%y",
year:"%d.%m.%y"}},yAxis:[{id:"axyValue",labels:{format:"{value} %",style:{color:Highcharts.getOptions().colors[2]}},tickPixelInterval:35,title:{text:"Taxa",style:{color:Highcharts.getOptions().colors[2]}},opposite:!1},{id:"axyPrice",tickPixelInterval:35,gridLineWidth:0,title:{text:"Pre\u00e7o",style:{color:Highcharts.getOptions().colors[0]}},labels:{format:"R$ {value}",style:{color:Highcharts.getOptions().colors[0]}}}],tooltip:{shared:!0,valueDecimals:2},legend:{layout:"vertical",align:"left",x:120,
verticalAlign:"top",y:100,floating:!0,backgroundColor:"#FFFFFF"}};a=$("#"+a);a.highcharts("StockChart",d);c._chart=a.highcharts()};this.LoadBond=function(a){c.checkSelectedBonds();var b;return c.getBondData(a).then(function(d){b=d.Taxs[0][0];var e=c._chart.get(a.TaxKey());a.IsTaxVisible&&null==e?c.createTaxaSerie(d,a.TaxKey(),a.ShortName):c.SetSerieVisibility(a.TaxKey(),a.IsTaxVisible);e=c._chart.get(a.PriceKey());a.IsPriceVisible&&null==e?c.createPriceSerie(d,a.PriceKey(),a.ShortName):c.SetSerieVisibility(a.PriceKey(),
a.IsPriceVisible);a.IsTaxAvaregeVisible?c._chart.addSeries({name:"M\u00e9dia M\u00f3vel 15-dias Taxa"+a.ShortName,id:a.TaxKeyMm(),linkedTo:a.TaxKey(),showInLegend:!0,type:"trendline",algorithm:"SMA",periods:15,yAxis:0},!1):c.SetSerieVisibility(a.TaxKeyMm(),a.IsTaxAvaregeVisible);a.IsPriceAvaregeVisible?c._chart.addSeries({name:"M\u00e9dia M\u00f3vel 15-dias Pre\u00e7o"+a.ShortName,id:a.PriceKeyMm(),linkedTo:a.PriceKey(),showInLegend:!0,type:"trendline",algorithm:"SMA",periods:15,yAxis:1},!1):c.SetSerieVisibility(a.PriceKeyMm(),
a.IsPriceAvaregeVisible)}).then(function(){c._indicesList.forEach(function(a){if(a.IsSelected){var d=c._chart.series.filter(function(b){return b.options.id==a.IndiceKey()})[0];c.getIndiceData(a,b).then(function(a){d.setData(a)})}});c._chart.redraw()})};this.GetBondByNameMaturityDate=function(a,b,e){return c._bondList.filter(function(c){return c.Bond===a&&c.MaturityDate.valueOf()===b.valueOf()&&c.Cupom==e})[0]};this.GetBondById=function(a){return c._bondList.filter(function(b){return b.Id===a})[0]};
this.createChart(a);this.setLocalization()};b.prototype.Init=function(){this.checkVisibility()};b.prototype.SetBondList=function(a){this._bondList=a};b.prototype.SetIndiceList=function(a){this._indicesList=a};b.prototype.checkSelectedBonds=function(){var a=this,b=this._bondList.filter(function(a){return a.IsSelected()});1<b.length&&(this.SetSerieVisibility("linearserie",!1),b.forEach(function(b){b.IsPriceAvaregeVisible=!1;b.IsTaxAvaregeVisible=!1;a.SetSerieVisibility(b.PriceKeyMm(),b.IsPriceAvaregeVisible);
a.SetSerieVisibility(b.TaxKeyMm(),b.IsTaxAvaregeVisible)}))};b.prototype.createTaxaSerie=function(a,b,c){this._chart.addSeries({name:"Taxa "+c,type:"spline",id:b,data:a.Taxs,yAxis:0,marker:{enabled:!0,radius:2},tooltip:{valueSuffix:" %"}},!1)};b.prototype.createPriceSerie=function(a,b,c){this._chart.addSeries({name:"Pre\u00e7o "+c,type:"spline",id:b,data:a.Prices,yAxis:1,marker:{enabled:!0,radius:2},tooltip:{valuePrefix:"R$ "}},!1)};b.prototype.LoadIndice=function(a,b){var c=this,d=this._indicesList.filter(function(b){return b.Type==
a})[0],e=this._bondList.filter(function(a){return a.IsSelected()})[0];this.getIndiceData(d,e?e.StarDate.valueOf():null).then(function(a){d.IsSelected=b;var e=c._chart.get(d.IndiceKey());d.IsSelected&&null==e?c._chart.addSeries({id:d.IndiceKey(),name:d.DisplayName,type:"spline",data:a,yAxis:0,tooltip:{valueSuffix:" %",shared:!1}},!1):c.SetSerieVisibility(d.IndiceKey(),d.IsSelected);c._chart.redraw()})};b.prototype.getBondData=function(a){return new Promise(function(b){var e=new c.BondPrice,d=a.BondKey(),
g=sessionStorage.getItem(d);if(g)e=JSON.parse(g),b(e);else{debugger;$.getJSON(c.DataServiceHelper.GetFullUrl(a.File),function(c){var f=c.map(function(a){return[a.TimeStamp,a.TxCompra]});c=c.map(function(a){return[a.TimeStamp,a.PuCompra]});e.BondId=a.Id;e.Prices=c;e.Taxs=f;f=JSON.stringify(e);sessionStorage.setItem(d,f);b(e)})}})};b.prototype.getIndiceData=function(a,b){b=void 0===b?null:b;var e=this;return new Promise(function(d){var f,h=a.IndiceKey(),k=a.File+".json",l=sessionStorage.getItem(h);
l?(f=JSON.parse(l),f=e.filterData(f,b),d(f)):$.getJSON(c.DataServiceHelper.GetFullUrl(k),function(a){f=a.map(function(a){return[a.Date,a.Value]});a=JSON.stringify(f);sessionStorage.setItem(h,a);f=e.filterData(f,b);d(f)})})};b.prototype.filterData=function(a,b){return b?a.filter(function(a){return a[0]>=b}):a};b.prototype.SetLinearPrice=function(a,b){var e=this,d=this._chart.series.filter(function(a){return"linearserie"==a.options.id})[0];if(b){var g=this._bondList.filter(function(a){return a.IsSelected()})[0];
return this.getBondData(g).then(function(f){var h=new Date(f.Prices[0][0]);if(null==a||a.valueOf()<h.valueOf())a=h;g.IsPriceAvaregeVisible=!1;g.IsTaxAvaregeVisible=!1;e.SetSerieVisibility(g.PriceKeyMm(),!1);e.SetSerieVisibility(g.TaxKey(),!1);f=f.Prices.filter(function(b){return b[0]>=a.valueOf()});var l=f[0][1],p=(g.MaturityDate.valueOf()-a.valueOf())/1E3/60/60/24,m=(1E3-l)/(p-p/7*2),n=[];f.forEach(function(a,b){n.push([a[0],0==n.length?l:n[b-1][1]+m])});null==d||void 0==d?e._chart.addSeries({id:"linearserie",
name:"Pre\u00e7o Linear",type:"spline",data:n,yAxis:1,tooltip:{valuePrefix:"R$ ",shared:!1}},!1):(d.setData(n,!1),d.setVisible(b,!1));e._chart.redraw();f=new c.LinearPrice;f.StartDate=h;return f})}d&&d.setVisible(b,!1)};b.prototype.GetActivedBonds=function(){return this._bondList.filter(function(a){return a.IsSelected()})};b.prototype.AddSerie=function(a){this._chart.addSeries(a,!0);this._chart.xAxis[0].setExtremes(0)};b.prototype.DisableAxi=function(a){this._chart.get(a).remove()};b.prototype.SetSerieVisibility=
function(a,b){var c=this._chart.series.filter(function(b){return b.options.id==a})[0];c&&c.setVisible(b,!1)};b.prototype.checkVisibility=function(){var a=this;this._bondList.forEach(function(b){if(b.IsSelected())a.LoadBond(b);else{var c="precoserieid"+b.Id;a.SetSerieVisibility("taxaserieid"+b.Id,!1);a.SetSerieVisibility(c,!1)}});this._indicesList.forEach(function(b){b.IsSelected?a.LoadIndice(b.Type,b.IsSelected):a.SetSerieVisibility(b.IndiceKey(),!1)})};b.prototype.setLocalization=function(){Highcharts.setOptions({global:{useUTC:!1},
lang:{decimalPoint:",",thousandsSep:".",contextButtonTitle:"Imprimir/Baixar gr\u00e1fico.",printChart:"Imprimir",downloadPNG:"Exportar para PNG",downloadJPEG:"Exportar para JPEG",downloadPDF:"Exportar para PDF",downloadSVG:"Exportar para SVG",resetZoom:"Reset Zoom",resetZoomTitle:"",months:"Janeiro Fevereiro Mar\u00e7o Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro".split(" "),shortMonths:"Jan Fev Mar Abr Mai Jun Jul Ago Set Out Nov Dez".split(" "),weekdays:"Domingo Segunda Ter\u00e7a Quarta Quinta Sexta S\u00e1bado".split(" ")}})};
c.ChartHandler=b})(TesouroGraficosModule||(TesouroGraficosModule={}));(function(c){c.ContactController=function(b){this.$scope=b}})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(){};b.GetDefaultUrl=function(){return window.location.origin+"/"};b.GetBondsList=function(){return b.GetDefaultUrl()+"App_Repo/Bonds.json"};b.GetIndices=function(){return b.GetDefaultUrl()+"App_Repo/Indices.json"};b.GetSelicFull=function(){return b.GetDefaultUrl()+"App_Repo/Selic_full.json"};b.GetFullUrl=function(a){return b.GetDefaultUrl()+a};c.DataServiceHelper=b})(TesouroGraficosModule||(TesouroGraficosModule={}));
(function(c){var b=function(){};b.prototype.IsSelected=function(){return this.IsPriceVisible||this.IsPriceAvaregeVisible||this.IsTaxVisible||this.IsTaxAvaregeVisible};b.prototype.BondUrl=function(){var a=this.Vencido?"/vencido":"";return this.Cupom?c.DataServiceHelper.GetDefaultUrl()+"#/titulo"+a+"/"+this.Bond+"/"+this.MaturityDate.ddmmyyyy()+"/cupom-de-juros":c.DataServiceHelper.GetDefaultUrl()+"#/titulo"+a+"/"+this.Bond+"/"+this.MaturityDate.ddmmyyyy()};b.prototype.BondKey=function(){return(new Date).yyyymmdd()+
"|"+this.Id};b.prototype.TaxKey=function(){return"taxaserieid"+this.Id};b.prototype.TaxKeyMm=function(){return"mmtaxaserieid"+this.Id};b.prototype.PriceKey=function(){return"precoserieid"+this.Id};b.prototype.PriceKeyMm=function(){return"mmprecoserieid"+this.Id};c.Bond=b;c.BondPrice=function(){};b=function(){};b.prototype.IndiceUrl=function(){return c.DataServiceHelper.GetDefaultUrl()+"#/indice/"+this.Name};b.prototype.IndiceKey=function(){return(new Date).yyyymmdd()+"|"+this.Type};c.Indice=b;c.LinearPrice=
function(){}})(TesouroGraficosModule||(TesouroGraficosModule={}));(function(c){c.IndiceViewModel=function(){}})(TesouroGraficosModule||(TesouroGraficosModule={}));Date.prototype.yyyymmdd=function(){var c=(this.getMonth()+1).toString(),b=this.getDate().toString();return[this.getFullYear(),2===c.length?"":"0",c,2===b.length?"":"0",b].join("")};Date.prototype.ddmmyyyy=function(){var c=(this.getMonth()+1).toString(),b=this.getDate().toString();return[2===b.length?"":"0",b,2===c.length?"":"0",c,this.getFullYear()].join("")};
